[package]
name = "ssa-traits"
version = "0.1.2"
edition = "2021"
license = "CC0-1.0"
description = "Traits for SSA IR"

[dependencies]
anyhow = "1.0"
arena-traits = { version = "0.1.0", path = "../arena-traits" }
either = "1.13.0"
