[package]
name = "ssa-traits"
version = "0.1.4"
edition = "2021"
license = "CC0-1.0"
description = "Traits for SSA IR"

[dependencies]
anyhow = {version="1.0",default-features=false}
arena-traits = { version = "0.1.0", path = "../arena-traits" }
either = {version="1.13.0",default-features=false}

[features]
std = ["anyhow/std"]
