[workspace]
members=["arena-traits", "ssa-traits", "ssa-impls",  "ssa-translation", "ssa-reloop", "ssa-cc", "sift-trait", "ssa-rust", "cfg-traits", "register-machine-traits", "tac-traits","onion","ssa-canon"] # , "ssa-trace"
# "ssa-canon","
resolver="2"

[workspace.dependencies]


id-arena = "2.2.1"
