[workspace]
members=["ssa-traits", "ssa-impls",  "ssa-translation", "ssa-reloop", "ssa-cc", "ssa-canon","sift-trait", "ssa-rust", "cfg-traits", "register-machine-traits", "tac-traits","onion"] # , "ssa-trace"
resolver="2"

[workspace.dependencies]


id-arena = "2.2.1"
