[package]
name = "ssa-impls"
version = "0.1.1"
edition = "2021"

[dependencies]
arena-traits = { version = "0.1.0", path = "../arena-traits" }
ssa-traits = { version = "0.1.0", path = "../ssa-traits" }
