[package]
name = "cfg-traits"
version = "0.3.0-alpha.0"
edition = "2021"
license = "CC0-1.0"
description = "Traits for Control Flow Graphs"

[dependencies]
arena-traits = { version = "0.2.2", path = "../arena-traits" }
either = "1.13.0"
lending-iterator = "0.1.7"
