[package]
name = "cfg-traits"
version = "0.2.1"
edition = "2021"
license = "CC0-1.0"
description = "Traits for Control Flow Graphs"

[dependencies]
arena-traits = { version = "0.2.3" }
either = "1.13.0"
