[package]
name = "arena-traits"
version = "0.1.2"
edition = "2021"
license = "CC0-1.0"
description = "Traits for arenas"

[dependencies]
id-arena = { workspace = true, optional = true }

[features]
id-arena = ["dep:id-arena"]
