[package]
name = "siftify"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
description = "Traits for arenas"

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.75", features = ["full"] }
